export interface RecipeGroup {
  group: string
  items: string[]
}

export const RECIPE_GROUPS: RecipeGroup[] = [
  {
    group: 'Detox 21',
    items: [
      'Smoothie de mere',
      'Ouă cu turmeric',
      'Cassoulet de pui la cuptor și fasole',
      'Iaurt cu trei semințe',
      'Linte cu ierburi',
      'Cod cu crustă de nuci și dovlecel aburit',
      'Mini Frittatas de Dovlecel',
      'Salată grecească de pui',
      'Scoici cu quinoa și praz crocant',
      'Toast cu cartofi dulci',
      'Supă de pui cu tăiței',
      'Creveți Scampi peste Spaghetti Squash',
      'Smoothie cu banane și mure',
      'Supă picantă de pui cu nucă de cocos',
      'Somon copt și sparanghel',
      'Kimchi Breakfast Bowl',
      'Somon în fulgi peste verdeață',
      'Tocană de fasole cu condimente indiene cu naan fără gluten',
      'Berry Parfait',
      'Ouă poșate peste dovleac',
      'Pui cu coriandru și salată de citrice Jicama',
      'Ovăz peste noapte',
      'Pui măruntit în bărci de andive',
      'Cartofi dulci umpluți',
      'Mere la cuptor',
      'Supersalata mega-microbiom',
      'Fajitas de pui cu "The Works"',
      'Smoothie de ciocolată, cireșe, nucă de cocos',
      'Falafel copt',
      'Creveți cu usturoi cu dovleac de vară la grătar',
      'Terci de orez brun',
      'GG Reubens',
      'Șofran și Cod',
      'Smoothie cu citrice',
      'Quinoa Tabbouleh',
      'Pulpe de pui condimentate și fasole verde Amandine',
      'Somon Scramble',
      'Bol cu proteine',
      'Supa de cocos',
      'Totul "Bagels"',
      'Bărci cu ton',
      '"Chowder" de scoici',
      'Kefir Latte',
      'Quinoa "Sushi"',
      'Pui cu lamaie, rozmarin și topinambur',
      'Clătite cu afine',
      'Avocado Milk Shake',
      'Somon cu sos de muștar și praz crocant',
      'Ulm alunecos cu fructe de pădure',
      'Salată de pui cu quinoa',
      'Linte cu curry și morcovi cu sos de tahini de lămâie',
    ],
  },
  {
    group: 'Microbiom — Săptămâna 1 (Ziua 1–7)',
    items: [
      'Microbiom Săpt.1 — Ziua 1',
      'Microbiom Săpt.1 — Ziua 2',
      'Microbiom Săpt.1 — Ziua 3',
      'Microbiom Săpt.1 — Ziua 4',
      'Microbiom Săpt.1 — Ziua 5',
      'Microbiom Săpt.1 — Ziua 6',
      'Microbiom Săpt.1 — Ziua 7',
    ],
  },
  {
    group: 'Microbiom — Săptămâna 2 (Ziua 8–14)',
    items: [
      'Microbiom Săpt.2 — Ziua 8',
      'Microbiom Săpt.2 — Ziua 9',
      'Microbiom Săpt.2 — Ziua 10',
      'Microbiom Săpt.2 — Ziua 11',
      'Microbiom Săpt.2 — Ziua 12',
      'Microbiom Săpt.2 — Ziua 13',
      'Microbiom Săpt.2 — Ziua 14',
    ],
  },
  {
    group: 'Microbiom — Săptămâna 3 (Ziua 15–21)',
    items: [
      'Microbiom Săpt.3 — Ziua 15',
      'Microbiom Săpt.3 — Ziua 16',
      'Microbiom Săpt.3 — Ziua 17',
      'Microbiom Săpt.3 — Ziua 18',
      'Microbiom Săpt.3 — Ziua 19',
      'Microbiom Săpt.3 — Ziua 20',
      'Microbiom Săpt.3 — Ziua 21',
    ],
  },
  {
    group: 'Microbiom — Săptămâna 4 (Ziua 22–28)',
    items: [
      'Microbiom Săpt.4 — Ziua 22',
      'Microbiom Săpt.4 — Ziua 23',
      'Microbiom Săpt.4 — Ziua 24',
      'Microbiom Săpt.4 — Ziua 25',
      'Microbiom Săpt.4 — Ziua 26',
      'Microbiom Săpt.4 — Ziua 27',
      'Microbiom Săpt.4 — Ziua 28',
    ],
  },
  {
    group: 'Microbiom — Săptămâna 5 (Ziua 29–35)',
    items: [
      'Microbiom Săpt.5 — Ziua 29',
      'Microbiom Săpt.5 — Ziua 30',
      'Microbiom Săpt.5 — Ziua 31',
      'Microbiom Săpt.5 — Ziua 32',
      'Microbiom Săpt.5 — Ziua 33',
      'Microbiom Săpt.5 — Ziua 34',
      'Microbiom Săpt.5 — Ziua 35',
    ],
  },
  {
    group: 'Microbiom — Săpt. 6+ (Smoothie-uri și Shake-uri)',
    items: [
      'Smoothie Verde Foarte Sănătos',
      'Smoothie cu Kiwi și Spanac',
      'Smoothie cu Căpșuni și Ghimbir',
      'Smoothie cu Mentă și Zmeură',
      'Smoothie cu Fructe de Pădure și Cremă',
      'Smoothie Super Verde Picant',
      'Smoothie cu Lapte de Migdale și Nucă de Cocos',
      'Smoothie Chai cu Turmeric',
    ],
  },
  {
    group: 'Microbiom — Săpt. 6+ (Mic Dejun)',
    items: [
      'Omletă Rapidă cu Legume',
      'Budincă de Chia cu Cocos',
      'Ruladă cu Castravete și Somon',
      'Sote Rapid cu Spanac, Ciuperci & Tempeh',
      'Clătite din Făină de Cocos',
      'Brioșe cu Ou și Legume',
      'Brioșe cu Zmeură și Lămâie',
      'Brioșe de dimineață cu Morcov',
      'Frittata cu Spanac, Dovlecel, Ceapă și Verdețuri Proaspete',
      'Chifteluțe Sărate pentru Mic Dejun',
      'Omletă cu Verdețuri Persane',
      'Shakshuka Verde cu Spanac și Sparanghel (VEG)',
    ],
  },
  {
    group: 'Microbiom — Săpt. 6+ (Prânz)',
    items: [
      'Wraps de Curcan & Avocado',
      'Lingurițe cu Somon, Salată de Castraveți și Dressing Tahini',
      'Wrap-uri cu Legume și Tempeh',
      'Salată Crocantă cu Verdețuri',
      'Salată Caesar cu Pui la Grătar',
      'Avocado Umplut cu Salată de Pui și Cremă de Caju',
      'Cremă de Avocado pe Verdețuri și Tofu Japonez (VEG)',
      'Salată Taco',
      'Wraps cu Somon',
      'Bol Sud-Vest',
      'Bol cu Friptură și Legume',
    ],
  },
  {
    group: 'Microbiom — Săpt. 6+ (Legume)',
    items: [
      'Salată de Ridichi cu Mentă și Oțet Balsamic (VEG)',
      'Castraveți Persani (V)',
      'Salată Simplă cu dressing (V)',
      'Verdețuri de Susan (V)',
    ],
  },
  {
    group: 'Microbiom — Săpt. 6+ (Cină)',
    items: [
      'Pui cu Lămâie și Legume',
      'Chifteluțe Mediteraneene din Curcan și Legume',
      'Creveți și Broccoli cu Lămâie',
      'Pui Picant cu Legume (V)',
      'Tavă Fajita cu Pui',
      'Pește la Cuptor cu Fasole Verde',
      'Tofu & Legume Curcubeu (V)',
      'Pui la Slow Cooker',
      'Chiftele de Somon la Cuptor',
      'Sardine cu Ierburi și Sos Avocado-Broccoli',
      'Vinete Umplute cu Nuci și Ciuperci',
      'Frigărui de Migdale cu Fasole Verde',
      'Chifteluțe de Miel cu Salată de Castraveți și Sos "Iaurt" din Caju',
      'Tocană Bistro cu Vită și Legume',
      'Supă de Ciuperci cu Lapte de Nuci',
      'Pește în Sos Catifelat de Roșii',
      'Somon Glazurat cu Miso și Orez de Conopidă cu Coriandru',
      'Cod cu Roșii, Capere și Usturoi',
      'Cod Oreganata',
      'Burgeri "Inside-Out"',
      'Shawarma de Pui de Casă cu Salată Israeli',
      'Somon cu Coriandru și Sos de Roșii',
      'Friptură de Vită cu Sos Romesco Spaniol',
      'Piept de Pui Rapid',
      'Pui înăbușit cu Sos de Caju',
      'Ardei Umpluți',
    ],
  },
  {
    group: 'Microbiom — Săpt. 6+ (Sosuri, Garnituri și Deserturi)',
    items: [
      '10 Gustări pe care le vei iubi',
    ],
  },
  {
    group: 'Microbiom — Săpt. 6+ (Apă Infuzată)',
    items: [
      'Apă Electrolitică cu Lămâie și Lime',
      'Apă Electrolitică cu Castravete și Mentă',
      'Apă Electrolitică cu Oțet de Mere',
      'Apă Electrolitică cu Castravete',
      'Apă Electrolitică cu Verdețuri',
    ],
  },
  {
    group: 'Tiroidă — Mic Dejun',
    items: [
      'Smoothie de mere',
      'Iaurt cu trei semințe',
      'Mini Frittatas de Dovlecel',
      'Toast cu cartofi dulci',
      'Smoothie cu banane și mure',
      'Kimchi Breakfast Bowl',
      'Berry Parfait',
      'Ovăz peste noapte',
      'Mere la cuptor',
      'Smoothie de ciocolată, cireșe, nucă de cocos',
      'Terci de orez brun',
      'Smoothie cu citrice',
      'Somon Scramble',
      'Totul „Bagels"',
      '1-2-3 Ovăz, 5 feluri',
      'Parfait de dovleac',
      'Smoothie tiroidian „Thy Best"',
      'Brioșe pentru mic dejun Pumpkin Spice',
      'Kefir Latte',
      'Clătite cu afine',
      'Ulm alunecos cu fructe de pădure',
      'Mic dejun Fajitas',
      'Smoothie verde',
      'Căpșuni cu Naan',
      'Ouă poșate cu sparanghel',
      'Tropical Parfait',
      'Lemon Chiffon',
      'Mic dejun Quinoa',
      'Ouă fierte tari cu hamsii',
      'Thy-Nola',
    ],
  },
  {
    group: 'Tiroidă — Prânz',
    items: [
      'Ouă cu turmeric',
      'Linte cu ierburi',
      'Salată grecească de pui',
      'Supă de pui cu tăiței',
      'Supă picantă de pui cu nucă de cocos',
      'Somon în fulgi peste verdeață',
      'Ouă poșate peste dovleac',
      'Pui măruntit în bărci de andive',
      'Supersalata mega-microbiom',
      'Falafel copt',
      'GG Reubens',
      'Quinoa Tabbouleh',
      'Bol cu proteine',
      'Bărci cu ton',
      'Învelișuri din carne de crab',
      'Salată de fasole cu coriandru',
      'Salată de quinoa cu avocado',
      'Paste și ton',
      'Quinoa „Sushi"',
      'Avocado Milk Shake',
      'Salată de pui cu quinoa',
      'Anghinare la abur cu sos tahini',
      'Salată de ton mediteraneană',
      'Tăiței cu dovlecel și pesto de pătrunjel',
      'Salata tiroidiană „Thy-Best"',
      'Cocktail de creveți cu dressing de avocado',
      'Burgeri cu somon și salată de Napi',
      'Supă cremoasă de năut',
      'Salată de rodii și citrice',
      'Supă de castraveți',
    ],
  },
  {
    group: 'Tiroidă — Cină',
    items: [
      'Cassoulet de pui la cuptor și fasole',
      'Cod cu crustă de nuci și dovlecel aburit',
      'Scoici cu quinoa și praz crocant',
      'Creveți Scampi peste Spaghetti Squash',
      'Somon copt și sparanghel',
      'Tocană de fasole cu condimente indiene cu naan fără gluten',
      'Pui cu coriandru și salată de citrice Jicama',
      'Cartofi dulci umpluți',
      'Fajitas de pui cu „The Works"',
      'Creveți cu usturoi cu dovleac de vară la grătar',
      'Șofran și Cod',
      'Pulpe de pui condimentate și fasole verde Amandine',
      'Supa de cocos',
      '„Chowder" de scoici',
      'Spaghetti Squash și Chiftele de curcan',
      'Somon cu sos de iaurt, mărar și salată de castraveți dulci-acrișori',
      'Halibut cu ghimbir în bulion',
      'Easy Turkey Chili',
      'Pui cu lamaie, rozmarin și topinambur',
      'Somon cu sos de muștar și praz crocant',
      'Linte cu curry și morcovi cu sos de tahini de lămâie',
      'Dovleac și pui',
      'Cârnați, ardei și varză murată',
      'Halibut la cuptor cu sfeclă elvețiană',
      'Burgeri cu somon copt și salată Caesar',
      'Frittata de cârnați',
      'Scoici la grătar și kimchi',
      'Tortilla de pui și ceapă caramelizată',
      'Quinoa și caserola cu kale',
      'Burgeri cu fasole neagră și morcovi copți',
    ],
  },
]

export const ALL_RECIPES: string[] = RECIPE_GROUPS.flatMap(g => g.items)
